
FIND_PACKAGE(CMLIB REQUIRED COMPONENTS CMCONF)

CMCONF_INIT_SYSTEM("EXAMPLE_SYSTEM")

CMCONF_SET("VARIABLE_A" "system -> example_value")
CMCONF_SET("IS_IT_OK"   OFF)
CMCONF_SET("GOOGLE_URI" "google URI: https://google.com/")