##
#
# Standard CMake Module which can be used by FIND_PACKAGE(CMLIB COMPONENTS CMCONF) functionality.
#
# [Module init workflow]
# - include all CMCONF modules
#

CMAKE_MINIMUM_REQUIRED(VERSION 3.22 FATAL_ERROR)

SET(CMDEF_PACKAGE_NAME "CMCONF")

SET(${CMDEF_PACKAGE_NAME}_FOUND 1)
SET(${CMDEF_PACKAGE_NAME}_DIR "${CMAKE_CURRENT_LIST_DIR}")

INCLUDE_GUARD(GLOBAL)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/CMCONF.cmake)

