
#FIND_PACKAGE(CMLIB REQUIRED COMPONENTS CMCONF)
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/../../CMCONF.cmake")

CMCONF_INIT_SYSTEM("TEST_CASE_SENSITIVE")

CMCONF_SET("Variable_Mixed_Case" "mixed_case_value")
