#FIND_PACKAGE(CMLIB REQUIRED COMPONENTS CMCONF)
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/../../CMCONF.cmake")

CMCONF_INIT_SYSTEM("TEST_SYSTEM")

CMCONF_SET("SYSTEM_VAR" "system_value")
CMCONF_SET("VARIABLE_A" "test_system_value_a")
